/**
 * Precomputed minimal-symbol ("par") solutions for every puzzle in the daily
 * dataset. Generated by `npm run generate:pars` (scripts/generatePars.ts),
 * which exhaustively searches the game's operator space and verifies every
 * candidate with mathjs — the shipped par is always an achievable solution.
 */
import parData from '../../puzzles/par_data.json';
import { operatorTokens, expressionShape } from './solver';

export interface ParInfo {
  par: number;
  expression: string;
}

type ParMap = { [seed: string]: { [target: string]: ParInfo } };

const data = parData as ParMap;

export const getParInfo = (seed: number, target: number): ParInfo | undefined =>
  data[seed.toString()]?.[target.toString()];

const displayOperator = (op: string): string => (op === '*' ? '×' : op);

export interface Hint {
  label: string;
  text: string;
}

/**
 * The three-step hint ladder for a puzzle, derived from its par solution:
 *  1. how many operators the par solution uses
 *  2. one of those operators
 *  3. the parenthesization shape with all numbers hidden
 */
export const buildHints = (parInfo: ParInfo): Hint[] => {
  const operators = operatorTokens(parInfo.expression);
  const revealed = operators.length > 0 ? displayOperator(operators[0]) : '?';
  return [
    {
      label: 'Operator count',
      text: `The par solution uses ${operators.length} operator${operators.length === 1 ? '' : 's'}`,
    },
    {
      label: 'One operator',
      text: `One of its operators is ${revealed}`,
    },
    {
      label: 'Solution shape',
      text: expressionShape(parInfo.expression).replace(/\*/g, '×'),
    },
  ];
};

export const TOTAL_HINTS = 3;
